steps:
  # Build the container image with Firebase config
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_FIREBASE_API_KEY=$_VITE_FIREBASE_API_KEY'
      - '--build-arg'
      - 'VITE_FIREBASE_AUTH_DOMAIN=$_VITE_FIREBASE_AUTH_DOMAIN'
      - '--build-arg'
      - 'VITE_FIREBASE_PROJECT_ID=$_VITE_FIREBASE_PROJECT_ID'
      - '--build-arg'
      - 'VITE_FIREBASE_APP_ID=$_VITE_FIREBASE_APP_ID'
      - '-t'
      - 'europe-west2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/south-hampshire-college'
      - '.'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/south-hampshire-college']

  # Deploy container image to Cloud Run with runtime secrets
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'southhampshirecollege'
      - '--image'
      - 'europe-west2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/south-hampshire-college'
      - '--region'
      - 'europe-west2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GEMINI_API_KEY=$_GEMINI_API_KEY,VITE_FIREBASE_API_KEY=$_VITE_FIREBASE_API_KEY,VITE_FIREBASE_AUTH_DOMAIN=$_VITE_FIREBASE_AUTH_DOMAIN,VITE_FIREBASE_PROJECT_ID=$_VITE_FIREBASE_PROJECT_ID,VITE_FIREBASE_APP_ID=$_VITE_FIREBASE_APP_ID'

# Substitution variables - pass these when running gcloud builds submit
substitutions:
  _GEMINI_API_KEY: ''
  _VITE_FIREBASE_API_KEY: ''
  _VITE_FIREBASE_AUTH_DOMAIN: ''
  _VITE_FIREBASE_PROJECT_ID: ''
  _VITE_FIREBASE_APP_ID: ''

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'europe-west2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/south-hampshire-college'
